
trigger:
- master

# strategy is to create multiple agents
strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    windows:
      operatingSystem: 'windows-2019'
pool:
  vmImage: $(operatingSystem)
  
stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - script: echo "Stage-Build and Job-Job1"
    - bash: echo $(variable1)
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
- stage: Dev
  dependsOn: Build
  jobs:
  - job: Job2
    steps:
    - script: echo "Stage-Dev and Job-Job2"
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'test-artiact'
        publishLocation: 'Container'


#- stage: Prod
#  jobs:
#  - job: Job3
#    steps:
#    - script: echo "Stage-Prod and Job-Job3"

