
trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - script: echo "Stage-Build and Job-Job1"

- stage: Dev
  jobs:
  - job: Job2
    steps:
    - script: echo "Stage-Dev and Job-Job2"

- stage: Prod
  jobs:
  - job: Job3
    steps:
    - script: echo "Stage-Prod and Job-Job3"

